### PR TITLE
Compatability with RN 0.29, also adding backward compatibility for apps using less than 0.29 version to work

### PR DESCRIPTION
**Pull request by vidyuthd**
The existing plugin won't work for 0.29 version of React Native.This is for making the plugin work with latest react native version (0.29+), refer to the breaking changes section of 0.29 for the changes - [here](https://github.com/facebook/react-native/releases/tag/v0.29.0).

Now the user has to just import the plugin as `new ReactSnackbarPackage()`.

### CODE REVIEW

**Comment by erickreutz** [comment]
Nice! So this is backwards compatible with < 0.29 correct?

**Comment by vidyuthd** [comment]
Yes, it is, I have tested with RN 0.27 too.

**Comment by vidyuthd** [comment]
Hi, I think we should hold of this change, it doesn't seem to be working well with other modules.  I have tested these changes in a project with multiple dependencies, so since each individual imports its own version of react-native and we don't know with which version the app will compile with and this changes strictly need latest react-native jar. This will result in compilation errors for the user. Hence we can't proceed. :(
